name: Project

on:
  issues:
    types:
      - opened

  pull_request:
    types:
      - opened

jobs:
  build:
    name: Add to project
    runs-on: ubuntu-latest

    steps:
      - name: Add To GitHub projects
        uses: actions/add-to-project@v1.0.0
        with:
          project-url: https://github.com/orgs/codelicia/projects/4
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}

